// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Projeto documents */
interface ProjetoDocumentData {
    /**
     * Título field in *Projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projeto.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Descrição field in *Projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projeto.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Tipo field in *Projeto*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: projeto.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    type: prismicT.KeyTextField;
    /**
     * Projeto Online field in *Projeto*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: projeto.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Thumbnail field in *Projeto*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: projeto.thumbnail
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    thumbnail: prismicT.ImageField<never>;
}
/**
 * Projeto document from Prismic
 *
 * - **API ID**: `projeto`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjetoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjetoDocumentData>, "projeto", Lang>;
export type AllDocumentTypes = ProjetoDocument;
/**
 * Primary content in Mywebsite → Primary
 *
 */
interface MywebsiteSliceDefaultPrimary {
    /**
     * Title field in *Mywebsite → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: mywebsite.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Mywebsite → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: mywebsite.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Mywebsite Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Mywebsite`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MywebsiteSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MywebsiteSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Mywebsite*
 *
 */
type MywebsiteSliceVariation = MywebsiteSliceDefault;
/**
 * Mywebsite Shared Slice
 *
 * - **API ID**: `mywebsite`
 * - **Description**: `Mywebsite`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MywebsiteSlice = prismicT.SharedSlice<"mywebsite", MywebsiteSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ProjetoDocumentData, ProjetoDocument, AllDocumentTypes, MywebsiteSliceDefaultPrimary, MywebsiteSliceDefault, MywebsiteSliceVariation, MywebsiteSlice };
    }
}
